#!/bin/sh
set -ue
aptly --config=.aptly.conf --keyring=`pwd`/trusted.gpg mirror create raspbian http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
aptly --config=.aptly.conf mirror edit  --filter="ansible|dracut|cpufrequtils|libnss-systemd|libpam-cap|xserver-xorg|openbox|xterm|fonts-droid-fallback|fonts-liberation2|xfonts-base|lightdm|x11-xserver-utils|python3-pyinotify|caffeine|vlc|okular|feh|libreoffice-impress|libreoffice-avmedia-backend-vlc" --filter-with-deps raspbian
aptly --config=.aptly.conf --keyring=`pwd`/trusted.gpg mirror update raspbian

aptly --config=.aptly.conf repo create himblick
# aptly --config=.aptly.conf repo add himblick fixed-vlc/*
# aptly --config=.aptly.conf repo add himblick ../../himblick_1.0-1_all.deb
