---
 - name: "Install exfat drivers"
   apt:
      name: exfat-fuse,exfat-utils
      state: present
      update_cache: no

 - name: "Create /srv directory"
   file:
      path: "/srv"
      state: directory
      owner: root
      group: root
      mode: 0755

 - name: "Create /media mount point"
   file:
      path: "/srv/media"
      state: directory
      owner: pi
      group: pi
      mode: 0755

 - name: "Configure mounting media directory"
   copy:
      src: srv-media.mount
      dest: /etc/systemd/system/srv-media.mount
      owner: root
      group: root
      mode: 0644

 - name: "Install media player dependencies"
   apt:
      pkg:
      # sets governor to ondemand at boot
       - cpufrequtils
      # basic system support not strictly needed
       - libnss-systemd
       - libpam-cap
      # basic X server
       - xserver-xorg
       # - xinit
       - openbox
       - xterm
       - fonts-droid-fallback
       - fonts-liberation2
       - xfonts-base
       - lightdm
      # himblick player dependencies
       - x11-xserver-utils  # for xrandr
       - python3-pyinotify
       - python3-tornado
       - libjs-jquery
       - libjs-bootstrap4
       - fonts-fork-awesome
       - caffeine
       - vlc
       - okular
       - feh
       - libreoffice-impress
       - libreoffice-avmedia-backend-vlc
      state: present
      update_cache: no
      install_recommends: no

 - name: "Enable lightdm autologin"
   lineinfile:
      path: /etc/lightdm/lightdm.conf
      regexp: ".*autologin-user\\s*=\\s*($|pi)"
      line: "autologin-user = pi"

 - name: "Disable mouse cursor in X"
   lineinfile:
      path: /etc/lightdm/lightdm.conf
      regexp: "(^|#)xserver-command\\s*=\\s*"
      line: "xserver-command = X -nocursor"

 - name: "Use himblick player as X session"
   copy:
      dest: /home/pi/.xsession
      owner: pi
      group: pi
      mode: '0644'
      content: |
          exec /usr/bin/himblick player
